djangocrm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from sales.views import 첫화면,첫화면View,회원가입View
from django.contrib.auth.views import LoginView,LogoutView

LoginView.template_name='회원가입/로그인.html'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',첫화면View.as_view()),
    path('홈페이지/', include('sales.urls', namespace="홈페이지")), 
    ##namespace = 링크가 바뀔 때 한번에 자동적으로 바뀔 수 있게하는장치!!!! 
    path('로그인/',LoginView.as_view(),name='로긴'),
    path('로그아웃/',LogoutView.as_view(), name='록아웃'),
    path('회원가입/',회원가입View.as_view(), name='가입'),
]

sales/urls.py
from django.urls import path
from .views import 세일목록,세일상세,세일_입력,세일_업데이트,세일_지우기,세일_입력View,세일목록View,세일상세View,세일_업데이트View,세일_지우기View

app_name = "홈페이지1111"
urlpatterns=[   ##철자주의
    path('',세일목록View.as_view(),name='목록'),
    path('<int:pk>/',세일상세View.as_view(),name="상세"), #<>안의 정보를 받음 #int안해주면 밑에도 숫자로입력해서문제생김
    path('ma_monde/',세일_입력View.as_view(),name='생성'),
    path('<int:pk>/업데이트/',세일_업데이트View.as_view(),name='업뎃'),
    path('<int:pk>/지우기/',세일_지우기View.as_view(),name='지우기'),
]

# <!--{% url namespace:name %}--> 
# ==namespace 에서 name을 찾아서 연결!!

sales/models.py
from signal import signal
from django.db import models
from django.contrib.auth.models import AbstractUser #이미있는 모델 가져오기 (회원관리)
from django.db.models.signals import post_save
# Create your models here. (DB)

class 아이디(AbstractUser): #상속 
    pass

class UserProfile(models.Model):
    회원 = models.OneToOneField(아이디, on_delete=models.CASCADE) #1대1

    def __str__(self) -> str:
        return self.회원.username

class Sale(models.Model):

    def __str__(self) -> str:  #클래스 자체를 출력할때 나오는거
        return self.last_name+self.first_name
    
    first_name = models.CharField(max_length=30) 
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(default=0)
    person = models.ForeignKey("Person", on_delete=models.CASCADE) #외래키
    #지워졌을경우
    #(CASCADE=같이지워짐)  (SET_NULL=null로 바꿈 null=True) (SET_DEFALT DEFALT로 바꿈 defalt='')

    # 기존고객 = models.BooleanField(default=False)
    # 인물사진 = models.ImageField(blank=True,null=True) #사진
    # 파일 = models.FileField(blank=True,null=True) #blank=빈채로저장허용 null=db null


class Person(models.Model):
    회원 = models.OneToOneField(아이디, on_delete=models.CASCADE) #1대1
    조직 = models.OneToOneField(UserProfile,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.회원.username

    #python manage.py migrate

def 회원생성signal(sender, instance, created, **kwargs): # 회원이 만들어지면 Userprofile자동으로 생성
    if created:
        UserProfile.objects.create(회원=instance)

post_save.connect(회원생성signal,sender=아이디) 
#회원이 생성되면, 만들어진 아이디 보내서 자동으로 추가


    

sales/forms.py
from django import forms
from .models import Sale
from django.contrib.auth.forms import UserCreationForm,UsernameField
from django.contrib.auth import get_user_model
User = get_user_model()
#입력등의 폼 이미정의되어있음

class SaleModelForm(forms.ModelForm): #필드지정할필요 x
    class Meta: #models에서 만들어놓은 모델 (sale)사용
        model=Sale
        fields= ( #보여줄 필드
            'first_name',
            'last_name',
            'age',
            'person'
        )


class SaleForm(forms.Form):
    first_name=forms.CharField()
    last_name=forms.CharField()
    age=forms.IntegerField(min_value=0)


class 우리만의UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields =("username",)
        field_classes = {'username' : UsernameField}

sales/views.py
from operator import ge
from django.shortcuts import render,redirect,reverse   #render=랜더링생각
from django.http import HttpResponse
from .models import Sale,Person
from .forms import SaleForm,SaleModelForm,우리만의UserCreationForm
from django.views import generic #장고 기본제공으로 한번에 만들기

# Create your views here.

class 회원가입View(generic.CreateView):
    template_name = "회원가입/가입.html"
    form_class = 우리만의UserCreationForm
    def get_success_url(self) :
        return reverse("로긴") 

class 첫화면View(generic.TemplateView):
    template_name = "첫화면.html"
################################
def 첫화면(request):
    return render(request, "첫화면.html") 


class 세일목록View(generic.ListView):
    template_name = "folder/세일목록.html"
    queryset= Sale.objects.all()
    context_object_name =  '사람키' #컨텍스트 집어넣기

##########################
def 세일목록(request):
    사람 = Sale.objects.all()
    context = {
        "사람키":사람
    }
    return render(request, "folder/세일목록.html", context) #context=html을 동적으로만드는 dict()
    #기본적으로 templates밑으로 바꿀러면 settings.py설정

class 세일상세View(generic.DetailView):
    template_name="folder/세일상세.html"
    queryset = Sale.objects.all()
    context_object_name = "사람키"
#############################
def 세일상세(request,pk): #urls.py에서받았던 pk를 받음
    # print(pk)
    사람 = Sale.objects.get(id=pk)
    # print(세일)
    
    context={
        "사람키":사람
    }
    return render(request,"folder/세일상세.html",context)

class 세일_입력View(generic.CreateView):
    template_name = "folder/세일_입력.html"
    form_class = SaleModelForm
    def get_success_url(self) :
        return reverse("홈페이지:목록") #redirect


def 세일_입력(request):
    폼=SaleModelForm()
    if request.method=='POST':
        폼 = SaleModelForm(request.POST)
        if 폼.is_valid(): #유효하면
            폼.save() #db에 저장

            return redirect("/홈페이지")

    context={
        "폼키": 폼,
    }

    return render(request,"folder/세일_입력.html",context)

class 세일_업데이트View(generic.UpdateView):
    template_name = "folder/세일_업데이트.html"
    queryset = Sale.objects.all()
    form_class = SaleModelForm
    context_object_name = "사람키"
    def get_success_url(self) -> str:
        return reverse("홈페이지:목록")

############################
def 세일_업데이트(request,pk):
    사람 = Sale.objects.get(id=pk)

    폼=SaleModelForm(instance=사람)
    if request.method=='POST':

        폼=SaleModelForm(request.POST,instance=사람)
        if 폼.is_valid():
            폼.save()
            return redirect("/홈페이지")
    context={
        "폼키":폼,
        "사람키" : 사람
        }
    
    return render(request,"folder/세일_업데이트.html",context)

class 세일_지우기View(generic.DeleteView):
    template_name = "folder/세일_지우기.html"
    queryset = Sale.objects.all()
    def get_success_url(self) :
        return reverse("홈페이지:목록")
###############################
def 세일_지우기(request,pk):
    사람=Sale.objects.get(id=pk)
    사람.delete()
    return redirect("/홈페이지")

""" def 세일_업데이트(request,pk):
    사람 = Sale.objects.get(id=pk)

    폼=SaleForm()
    if request.method=='POST':
        폼 = SaleForm(request.POST)
        if 폼.is_valid(): #유효성 체크
            first_name=폼.cleaned_data["first_name"]
            last_name=폼.cleaned_data["last_name"]
            age=폼.cleaned_data["age"]
            person=Person.objects.first()

            사람.first_name = first_name
            사람.last_name = last_name
            사람.age=age
            사람.save()

            return redirect("/홈페이지")
    context={
        "폼키":폼,
        "사람키" : 사람
        }
    
    return render(request,"folder/세일_업데이트.html",context) """
    
""" def 세일_입력(request):
    폼=SaleForm()
    if request.method=='POST':
        print("포스트 메소드로 왔네요")
        폼 = SaleForm(request.POST)
        if 폼.is_valid(): #유효성 체크
            print("유효")
            print(폼.cleaned_data)
            first_name=폼.cleaned_data["first_name"]
            last_name=폼.cleaned_data["last_name"]
            age=폼.cleaned_data["age"]
            person=Person.objects.first()

            Sale.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                person=person
            )

            print("세일이 입력 되었습니다")
            return redirect("/홈페이지")

    context={
        "폼키": 폼,
    }

    return render(request,"folder/세일_입력.html",context) """

sales/templates/folder/세일_업데이트.html
{% extends '와꾸.html' %}
{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
  
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{사람키.last_name}} {{사람키.first_name}}</h1>
          <div class="flex mb-11">
            <a href="{% url '홈페이지:상세' 사람키.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">고객 정보</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">평가</a>
            <a href="{% url  '홈페이지:업뎃' 사람키.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">정보수정</a>
          </div>
          <form method="post">
              {% csrf_token %}
              {{form.as_p}}
            <button type="submit" class=" flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">전송</a>

          </form>
        
          <button type="submit"><a  href="{% url '홈페이지:지우기' 사람키.pk %}" class=" flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">지우기</a></button>
        
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>
   

{% endblock content %}

sales/templates/folder/세일_입력.html
{% extends '와꾸.html' %}
{% block content %}
        <p>세일을 입력해 주세요</p>
       <form method="post">
           {% csrf_token %}   <!--보안을 위한 토큰-->
           <p>{{폼키.as_p}}</p>
        <button type="submit">전송</button>
    </form> 

{% endblock content %}

sales/templates/folder/세일_지우기.html
{% extends '와꾸.html' %}
{% block content %}
        <p>진짜 지워요?</p>
       <form method="post">
           {% csrf_token %}   <!--보안을 위한 토큰-->
          
        <button type="submit">전송</button>
    </form> 

{% endblock content %}

sales/templates/folder/세일목록.html
{% extends '와꾸.html' %}


{% block content %}


<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
  <div class="w-full">

<div><h1 class="text-blue-800">이것이 고객 목록 입니다.</h1></div>
<div class="mb-5 text-yellow-800"><a href="{% url '홈페이지:생성' %}">세일 만들기</a></div>
</div> 
      {% for 인간 in 사람키 %}
     
    <div class="flex flex-wrap -m-4">
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{인간.last_name}} {{인간.first_name}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href="{% url '홈페이지:상세' 인간.pk %}"  class="mt-3 text-indigo-500 inline-flex items-center">상세보기
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock content %}


        

sales/templates/folder/세일상세.html
{% extends '와꾸.html' %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">

        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{사람키.last_name}} {{사람키.first_name}}</h1>
        <div class="flex mb-11">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">고객 정보</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">평가</a>
          <a href="{% url  '홈페이지:업뎃' 사람키.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">정보수정</a>
        </div>
        <p class="leading-relaxed mb-4">짜정면을 좋아하시는 여러가지 문제를 연구하는 연구소 소장님.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">나이</span>
          <span class="ml-auto text-gray-900">{{사람키.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">지역</span>
          <span class="ml-auto text-gray-900">강원남도</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">연락처</span>
          <span class="ml-auto text-gray-900">412345567</span>
        </div>
        
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

{% endblock content %}

templates/메뉴.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">세일관리</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a href="{% url '홈페이지:목록' %}" class="mr-5 hover:text-gray-900">목록</a>
    {% if not request.user.is_authenticated %}
    <a href="{% url '가입' %}" class="mr-5 hover:text-gray-900">회원가입</a>
    {% endif %}
    </nav>
    {% if  request.user.is_authenticated %} <!--유저가 로그인됬으면-->
      {{request.user.username}}님은 로그인 했어요
      <a href="{% url '록아웃' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">로그아웃
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    {% else %}
    <a href="{% url '로긴' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">로그인
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

templates/아무거나2.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        
        <h1>아무거나 먹자</h1>
        <p> 점심 :  {{메뉴명}} </p>
       <p>예산 : {{가격}}  </p> 

    <p>
        드실분:
        <u1>
            {% for 드실사람들은 in 손님 %}
            <li>{{드실사람들은}}</li>
            {% endfor %}
        </u1>
    </p>

       <p>밥먹는 사람 : {{손님}}</p>
    </body>
</html>

templates/와꾸.html
<!DOCTYPE html>
<html>
    <head>
        <title> 타이틀 </title>
        <link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    </head>
    <body>
        <div class ="max-w-7xl mx-auto bg-grey-600 bg-opacity-75">
        {%  include "메뉴.html" %}
        {% block content %}
        
        {% endblock content %}

        {% include "프로그램.html" %}
    </div>

    </body>
</html>

templates/첫화면.html
{% extends "와꾸.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Microdosing synth tattooed vexillologist</h1>
        <p class="mb-8 leading-relaxed">장고 세일관리 입니다</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
        </div>
      </div>
    </div>
  </section>

  {% endblock content %}

templates/프로그램.html
<script>
    console.log('안녕')
</script>

templates/회원가입/가입.html
{% extends '와꾸.html' %}
{% block content %}
        <p>가입해 주세요</p>
       <form method="post">
           {% csrf_token %}   <!--보안을 위한 토큰-->
           <p>{{form.as_p}}</p>
        <button type="submit">전송</button>
    </form> 

{% endblock content %}

templates/회원가입/로그인.html
{% extends '와꾸.html' %}
{% block content %}
        <p>로그인 해 주세요</p>
       <form method="post">
           {% csrf_token %}   <!--보안을 위한 토큰-->
           <p>{{form.as_p}}</p>
        <button type="submit">전송</button>
    </form> 

{% endblock content %}